platform :ios, '7.0'
pod 'TheAmazingAudioEngine'
pod 'EZAudio', :path => 'Library/EZAudio/EZAudio.podspec'
pod 'CocoaSoundCloudAPI'
pod 'CocoaSoundCloudUI-iOS7', :path => 'Library/CocoaSoundCloudUI/CocoaSoundCloudUI.podspec'
pod 'SVProgressHUD'