platform :ios, '7.0'
pod 'TheAmazingAudioEngine', '~> 1.3'
pod 'EZAudio', :path => 'Library/EZAudio/EZAudio.podspec'
pod 'CocoaSoundCloudAPI', '1.0.1'
pod 'CocoaSoundCloudUI-iOS7', :path => 'Library/CocoaSoundCloudUI/CocoaSoundCloudUI.podspec'
pod 'SVProgressHUD'